# Generated by Django 5.1.4 on 2024-12-28 20:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('click', 'Click'), ('view', 'View'), ('submit', 'Submit'), ('upload', 'Upload'), ('download', 'Download')], help_text='Type of event.', max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When the event occurred.')),
                ('metadata', models.JSONField(blank=True, help_text='Additional data associated with the event (e.g., button clicked).', null=True)),
                ('user', models.ForeignKey(help_text='User who triggered the event.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_start', models.DateTimeField(default=django.utils.timezone.now, help_text='Session start time.')),
                ('session_end', models.DateTimeField(blank=True, help_text='Session end time.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the session originated.', null=True)),
                ('user', models.ForeignKey(help_text='User associated with the session.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_url', models.URLField(help_text='The URL of the page that was viewed.')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Time when the page was viewed.')),
                ('user', models.ForeignKey(help_text='User who viewed the page.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, help_text='Session during which the page was viewed.', null=True, on_delete=django.db.models.deletion.CASCADE, to='analytics.usersession')),
            ],
        ),
    ]
