# Generated by Django 5.1.4 on 2024-12-31 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('content', '0002_sitebookmark_siteemoji_sitereport'),
        ('forums', '0001_initial'),
        ('research', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageview',
            name='session',
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True, help_text='Date when the analytics data was published.')),
                ('type', models.CharField(help_text='Type of like (e.g., thumbs up, heart, etc.).', max_length=20)),
                ('article', models.ForeignKey(blank=True, help_text='Associated article.', null=True, on_delete=django.db.models.deletion.CASCADE, to='research.article')),
                ('blog', models.ForeignKey(blank=True, help_text='Associated blog.', null=True, on_delete=django.db.models.deletion.CASCADE, to='research.blog')),
                ('event', models.ForeignKey(blank=True, help_text='Associated event.', null=True, on_delete=django.db.models.deletion.CASCADE, to='research.event')),
                ('forum', models.ForeignKey(blank=True, help_text='Associated forum.', null=True, on_delete=django.db.models.deletion.CASCADE, to='forums.forum')),
                ('post', models.ForeignKey(blank=True, help_text='Associated post.', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.post')),
                ('user', models.ForeignKey(blank=True, help_text='Associated user.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Repost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True, help_text='Date when the analytics data was published.')),
                ('article', models.ForeignKey(blank=True, help_text='Associated article.', null=True, on_delete=django.db.models.deletion.CASCADE, to='research.article')),
                ('blog', models.ForeignKey(blank=True, help_text='Associated blog.', null=True, on_delete=django.db.models.deletion.CASCADE, to='research.blog')),
                ('event', models.ForeignKey(blank=True, help_text='Associated event.', null=True, on_delete=django.db.models.deletion.CASCADE, to='research.event')),
                ('forum', models.ForeignKey(blank=True, help_text='Associated forum.', null=True, on_delete=django.db.models.deletion.CASCADE, to='forums.forum')),
                ('post', models.ForeignKey(blank=True, help_text='Associated post.', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.post')),
                ('user', models.ForeignKey(blank=True, help_text='Associated user.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True, help_text='Date when the analytics data was published.')),
                ('where', models.CharField(help_text='Where the post was shared (e.g., social media platform).', max_length=50)),
                ('article', models.ForeignKey(blank=True, help_text='Associated article.', null=True, on_delete=django.db.models.deletion.CASCADE, to='research.article')),
                ('blog', models.ForeignKey(blank=True, help_text='Associated blog.', null=True, on_delete=django.db.models.deletion.CASCADE, to='research.blog')),
                ('event', models.ForeignKey(blank=True, help_text='Associated event.', null=True, on_delete=django.db.models.deletion.CASCADE, to='research.event')),
                ('forum', models.ForeignKey(blank=True, help_text='Associated forum.', null=True, on_delete=django.db.models.deletion.CASCADE, to='forums.forum')),
                ('post', models.ForeignKey(blank=True, help_text='Associated post.', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.post')),
                ('user', models.ForeignKey(blank=True, help_text='Associated user.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now=True, help_text='Date when the analytics data was published.')),
                ('device_type', models.CharField(help_text='Type of device used to view the post.', max_length=50)),
                ('os', models.CharField(help_text='Operating system of the device.', max_length=50)),
                ('browser', models.CharField(help_text='Browser used to view the post.', max_length=50)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the device.')),
                ('article', models.ForeignKey(blank=True, help_text='Associated article.', null=True, on_delete=django.db.models.deletion.CASCADE, to='research.article')),
                ('blog', models.ForeignKey(blank=True, help_text='Associated blog.', null=True, on_delete=django.db.models.deletion.CASCADE, to='research.blog')),
                ('event', models.ForeignKey(blank=True, help_text='Associated event.', null=True, on_delete=django.db.models.deletion.CASCADE, to='research.event')),
                ('forum', models.ForeignKey(blank=True, help_text='Associated forum.', null=True, on_delete=django.db.models.deletion.CASCADE, to='forums.forum')),
                ('post', models.ForeignKey(blank=True, help_text='Associated post.', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.post')),
                ('user', models.ForeignKey(blank=True, help_text='Associated user.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='PageView',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
