# Generated by Django 5.1.4 on 2025-01-01 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_role_socialrole_alter_account_options_and_more'),
        ('analytics', '0002_remove_pageview_session_remove_pageview_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Associated user.', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.visitor'),
        ),
        migrations.AlterField(
            model_name='repost',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Associated user.', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.visitor'),
        ),
        migrations.AlterField(
            model_name='share',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Associated user.', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.visitor'),
        ),
        migrations.AlterField(
            model_name='view',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Associated user.', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.visitor'),
        ),
    ]
