# Generated by Django 5.1.4 on 2024-12-31 15:24

import content.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.OneToOneField(help_text='Associated comment for the bookmark.', on_delete=django.db.models.deletion.CASCADE, to='content.comment')),
                ('post', models.ForeignKey(blank=True, help_text='Associated post for the bookmark.', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.post')),
                ('user', models.ForeignKey(help_text='User who makes the bookmark', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteEmoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('Like', 'Like'), ('Love', 'Love'), ('Haha', 'Haha'), ('Wow', 'Wow'), ('Sad', 'Sad'), ('Angry', 'Angry')], default='Like', help_text='Emoji reaction to the post/comment.', max_length=20)),
                ('comment', models.OneToOneField(help_text='Associated comment for the emoji reaction.', on_delete=django.db.models.deletion.CASCADE, to='content.comment')),
                ('post', models.ForeignKey(blank=True, help_text='Associated post for the emoji reaction.', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.post')),
                ('user', models.ForeignKey(help_text='User who makes the emoji reaction', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SiteReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.FileField(help_text='File containing message associated to user report', upload_to=content.models.reactions_dir_path)),
                ('category', models.CharField(choices=[('Spam', 'Spam'), ('Abuse', 'Abuse'), ('Inappropriate', 'Inappropriate'), ('Other', 'Other')], default='Spam', help_text='Category of the report.', max_length=20)),
                ('comment', models.OneToOneField(help_text='Associated comment for the report.', on_delete=django.db.models.deletion.CASCADE, to='content.comment')),
                ('post', models.ForeignKey(blank=True, help_text='Associated post for the report.', null=True, on_delete=django.db.models.deletion.CASCADE, to='content.post')),
                ('user', models.ForeignKey(blank=True, help_text='User who makes the report', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
