# Generated by Django 5.1.4 on 2024-12-28 20:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='The API endpoint accessed.', max_length=255)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], help_text='HTTP Method.', max_length=10)),
                ('request_body', models.JSONField(blank=True, help_text='Request body (if any).', null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the request.')),
                ('user_ip', models.GenericIPAddressField(blank=True, help_text='IP address of the user making the request.', null=True)),
                ('status_code', models.IntegerField(help_text='HTTP status code returned by the API.')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique API key.', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the API key was created.')),
                ('expired_at', models.DateTimeField(blank=True, help_text='Timestamp when the API key will expire.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the API key is active.')),
                ('user', models.ForeignKey(help_text='User associated with the API key.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='APIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_body', models.JSONField(help_text='Response body returned by the API.')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the response.')),
                ('status_code', models.IntegerField(help_text='HTTP status code of the response.')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.apirequest')),
            ],
        ),
    ]
