# Generated by Django 5.1.4 on 2024-12-28 20:37

import content.models
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of location', max_length=255)),
                ('description', models.FileField(help_text='Location describing the post content.', upload_to=content.models.acc_data_desc_dir_path)),
                ('added_by', models.CharField(help_text='name of locator', max_length=255)),
                ('address', models.CharField(help_text='Full address of the location.', max_length=255)),
                ('latitude', models.FloatField(help_text='Latitude of the location.')),
                ('longitude', models.FloatField(help_text='Longitude of the location.')),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Geographic coordinates (latitude, longitude).', srid=4326)),
            ],
        ),
    ]
