# Generated by Django 5.1.4 on 2024-12-28 20:37

import django.db.models.deletion
import tunes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_names', models.CharField(help_text='Admin names.', max_length=50)),
                ('password', models.CharField(help_text='Hashed administrator password.', max_length=254)),
                ('current_date', models.DateField(auto_now=True, help_text='Last updated date.')),
                ('account', models.OneToOneField(help_text='Associated admin account.', on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='Privilege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_valid', models.BooleanField(default=True, help_text='Indicates if the object is valid.')),
                ('owner', models.CharField(help_text='Who the privilege applies to.', max_length=50)),
                ('title', models.CharField(help_text='Title of the privilege.', max_length=50)),
                ('description', models.FileField(help_text='Description of the privilege.', upload_to=tunes.models.privilege_dir_path)),
                ('pub_date', models.DateField(auto_now=True, help_text='Last updated date.')),
                ('account', models.ForeignKey(blank=True, help_text='Account to which privilege applies if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('user', models.ForeignKey(blank=True, help_text='Custom user to which privilege applies if applicable.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('admin', models.ForeignKey(blank=True, help_text='Admin to which privilege applies if applicable.', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='tunes.wikiadmin')),
            ],
            options={
                'ordering': ['-pub_date'],
            },
        ),
    ]
